let num1=10
let num2=6
let igual=num1==num2;
console.log("comparacion==", igual);
let igualbinario=num1===num2;
console.log("comparacion===", igualbinario);
let diferente=num1!=num2;
console.log("comparacion!=", diferente);
let diferentebinar=num1!==num2;
console.log("comparacion!==", diferentebinar);
let mayorque=num1>num2;
console.log("comparacion>", mayorque);
let menorque=num1<num2;
console.log("comparacion<", menorque);
let mayoroigual=num1>=num2;
console.log("comparacion>=", mayoroigual);
